version: '3.1'
services:
  adminer:
    image: adminer
    restart: ${RESTART}
    ports:
      - ${ADMINER_PORT}:8080
  dbPostgres:
    image: postgres
    restart: ${RESTART}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}